'use client'

import { Save, Eye } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useAdminContent } from '@/lib/admin-data'
import AdminDataNotice from '@/components/admin/AdminDataNotice'

const starter = {
  profile: {
    name: 'Mukesh Khadka', role: 'Digital Systems & Software Portfolio', tagline: 'Software Systems • Web Platforms • Digital Transformation', availability: 'Co-founder & CEO at AashaTech', availabilityHref: 'https://aashatech.com/',
  },
  heroCopy: { eyebrow: 'Digital Systems & Software Portfolio', roleLine: 'Software Systems • Web Platforms • Digital Transformation', ctaPrimaryHref: '#work', ctaSecondaryHref: '#contact' },
  aboutCopy: { index: '01', eyebrow: 'About Mukesh', highlights: ['Practical software delivery', 'Clear digital presentation', 'Systems that support daily work'], resumeHref: '#contact', meta: [] },
  contactCopy: { index: '06', eyebrow: 'Contact', heading: 'Let’s make the next workflow clearer.', blurb: 'Share the problem, the people involved, and the outcome you need. We can shape the right digital solution from there.', studioFacts: [], workPrompts: [] },
  uiCopy: {
    navigation: { menuKicker: 'NAVIGATION / OPEN CHANNEL', menuDescription: 'Move through the work, the tools, and the thinking behind the systems.', sectionLinks: [{ label: 'About', href: '/#about' }, { label: 'Field Files', href: '/#work' }, { label: 'Skills', href: '/#skills' }, { label: 'History', href: '/#experience' }, { label: 'Contact', href: '/#contact' }], pageLinks: [{ label: 'Articles', href: '/articles' }, { label: 'Contact', href: '/contact' }] },
    projects: { index: '02', eyebrow: 'Work index', heading: 'Systems built for the work behind the work.', viewLabel: 'View', gridLabel: 'Grid', focusLabel: 'Focus', discussLabel: 'Discuss this system', openLabel: 'Open file', footerPrimary: 'systems / one working method', footerSecondary: 'From public records to everyday operations →' },
    skills: { index: '03', eyebrow: 'System Inventory', heading: 'What I can help you with.', readyLabel: 'Inventory ready', categoriesLabel: 'Categories', toolsLabel: 'Tools in rotation', statusLabel: 'Status', statusValue: 'live / production', practiceLabel: 'Practice live', toolboxLabel: 'Toolbox', toolboxCountLabel: 'tools in rotation' },
    experience: { index: '04', eyebrow: 'Operational History', heading: 'A timeline of the work that shaped me.', filedLabel: 'Filed under', entriesLabel: 'Entries', statusLabel: 'Status', statusValue: 'Live / compiling', footnote: 'Each entry is a chapter of the same practice — software, systems, and the people they serve. The dossier stays open.' },
    testimonials: { index: '05', eyebrow: 'Verified Reports', heading: 'What people say about working with me.', filedLabel: 'Filed under', transmissionsLabel: 'Transmissions', channelLabel: 'Channel', channelValue: 'Open / verified', footnote: 'Every report is paraphrased with the client’s permission. Names are kept where their organization allows; titles are kept where they help the story.' },
    contact: { terminalLabel: 'TRANSMISSION TERMINAL', statusValue: 'READY · STANDING BY', body: 'Inbound channels are open. Pick the one that fits the work — short briefs, ongoing partnerships, or a quick call to sense whether we should build together.', bodyMeta: 'Long-form briefs welcome. Short intros welcome. So are second opinions.', emailAction: 'Start an email', phoneAction: 'Call directly', footerLabel: 'Channel ready', wiresLabel: 'WIRES · outbound' },
    footer: { brandEyebrow: 'Colophon', statusValue: 'Studio live', compilerLabel: 'Compiler', navigationTitle: 'Navigation', servicesTitle: 'Services', studioTitle: 'Studio', wiresLabel: 'Wires · outbound', topLabel: 'Back to top' },
  },
}

function Field({ label, value, nepaliValue, onChange, onNepaliChange, multiline = false }: { label: string; value: string; nepaliValue?: string; onChange: (value: string) => void; onNepaliChange?: (value: string) => void; multiline?: boolean }) {
  const Control = multiline ? 'textarea' : 'input'
  return <div className="grid gap-3 sm:grid-cols-2"><label className="block space-y-1"><span className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label} / English</span><Control value={value} onChange={event => onChange(event.target.value)} rows={multiline ? 3 : undefined} className="admin-control w-full resize-y px-3 py-2" /></label><label className="block space-y-1"><span className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label} / नेपाली</span><Control value={nepaliValue || ''} onChange={event => onNepaliChange?.(event.target.value)} rows={multiline ? 3 : undefined} className="admin-control w-full resize-y px-3 py-2" /></label></div>
}

function JsonField({ label, value, onChange }: { label: string; value: unknown; onChange: (value: unknown) => void }) {
  const [text, setText] = useState(() => JSON.stringify(value ?? [], null, 2))
  useEffect(() => setText(JSON.stringify(value ?? [], null, 2)), [value])
  return <label className="block space-y-1"><span className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label} (JSON)</span><textarea value={text} onChange={event => { setText(event.target.value); try { onChange(JSON.parse(event.target.value)) } catch { /* keep editing until valid JSON */ } }} rows={5} className="admin-control w-full resize-y px-3 py-2 font-mono text-xs" /></label>
}

export default function SiteContentAdmin() {
  const { data, setData, save, loading, saving, error, usingStarter } = useAdminContent('pages', starter, { starterOnEmpty: false })
  const [saved, setSaved] = useState(false)
  const value = { ...starter, ...(data || {}), uiCopy: { ...starter.uiCopy, ...((data as any)?.uiCopy || {}) } } as typeof starter
  const update = (section: keyof typeof starter, key: string, next: unknown) => setData({ ...value, [section]: { ...(value[section] as object), [key]: next } })
  const updateUi = (section: keyof typeof starter.uiCopy, key: string, next: string) => setData({ ...value, uiCopy: { ...value.uiCopy, [section]: { ...value.uiCopy[section], [key]: next } } })
  const translations = ((value as any).translations || {}) as Record<string, { ne?: string }>
  const nepaliValue = (path: string) => translations[path]?.ne || ''
  const updateNepali = (path: string, next: string) => setData({ ...value, translations: { ...translations, [path]: { ...translations[path], ne: next } } } as typeof value)
  const bilingual = (label: string, path: string, english: string, onEnglishChange: (next: string) => void, multiline = false) => <Field label={label} value={english} nepaliValue={nepaliValue(path)} onChange={onEnglishChange} onNepaliChange={next => updateNepali(path, next)} multiline={multiline} />
  const handleSave = async () => { if (await save(value)) { setSaved(true); setTimeout(() => setSaved(false), 2000) } }

  return <div className="max-w-5xl space-y-6">
    <div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-gray-800">Landing Page Copy</h2><p className="text-sm text-gray-500">Edit the page-level copy used by the current public homepage.</p></div><div className="flex gap-2"><a href="/#work" target="_blank" className="admin-action flex items-center gap-2 rounded-lg px-4 py-2 text-sm"><Eye size={16} /> Preview</a><button onClick={() => void handleSave()} disabled={saving} className="admin-action admin-action--primary flex items-center gap-2 rounded-lg px-5 py-2 text-sm font-semibold disabled:opacity-50">{saving ? 'Saving…' : saved ? '✓ Saved' : <><Save size={16} /> Save copy</>}</button></div></div>
    <AdminDataNotice loading={loading} error={error} usingStarter={usingStarter} />
    <section className="admin-card grid gap-4 rounded-2xl p-5 md:grid-cols-2"><h3 className="md:col-span-2 font-semibold text-gray-800">Profile and navigation</h3>{(['name', 'role', 'tagline', 'availability'] as const).map(key => <div key={key}>{bilingual(key, `profile.${key}`, String((value.profile as any)[key] || ''), next => update('profile', key, next))}</div>)}<div>{bilingual('Menu kicker', 'uiCopy.navigation.menuKicker', value.uiCopy.navigation.menuKicker, next => updateUi('navigation', 'menuKicker', next))}</div><div>{bilingual('Menu description', 'uiCopy.navigation.menuDescription', value.uiCopy.navigation.menuDescription, next => updateUi('navigation', 'menuDescription', next), true)}</div><Field label="Availability link" value={value.profile.availabilityHref} onChange={next => update('profile', 'availabilityHref', next)} /><JsonField label="Section links" value={value.uiCopy.navigation.sectionLinks} onChange={next => updateUi('navigation', 'sectionLinks', next as any)} /><JsonField label="Page links" value={value.uiCopy.navigation.pageLinks} onChange={next => updateUi('navigation', 'pageLinks', next as any)} /></section>
    <section className="admin-card grid gap-4 rounded-2xl p-5 md:grid-cols-2"><h3 className="md:col-span-2 font-semibold text-gray-800">Hero and about labels</h3>{(['eyebrow', 'roleLine'] as const).map(key => <div key={key}>{bilingual(`Hero ${key}`, `heroCopy.${key}`, String((value.heroCopy as any)[key] || ''), next => update('heroCopy', key, next))}</div>)}<Field label="Hero primary link" value={value.heroCopy.ctaPrimaryHref} onChange={next => update('heroCopy', 'ctaPrimaryHref', next)} /><Field label="Hero secondary link" value={value.heroCopy.ctaSecondaryHref} onChange={next => update('heroCopy', 'ctaSecondaryHref', next)} />{(['index', 'eyebrow'] as const).map(key => <div key={key}>{bilingual(`About ${key}`, `aboutCopy.${key}`, String((value.aboutCopy as any)[key] || ''), next => update('aboutCopy', key, next))}</div>)}<Field label="About link" value={value.aboutCopy.resumeHref} onChange={next => update('aboutCopy', 'resumeHref', next)} /><JsonField label="About highlights" value={value.aboutCopy.highlights} onChange={next => update('aboutCopy', 'highlights', next)} /><JsonField label="About metadata" value={value.aboutCopy.meta} onChange={next => update('aboutCopy', 'meta', next)} /></section>
    <section className="admin-card grid gap-4 rounded-2xl p-5 md:grid-cols-2"><h3 className="md:col-span-2 font-semibold text-gray-800">Contact section</h3>{(['index', 'eyebrow', 'heading'] as const).map(key => <div key={key}>{bilingual(key, `contactCopy.${key}`, String((value.contactCopy as any)[key] || ''), next => update('contactCopy', key, next), key === 'heading')}</div>)}<div className="md:col-span-2">{bilingual('Blurb', 'contactCopy.blurb', value.contactCopy.blurb, next => update('contactCopy', 'blurb', next), true)}</div><JsonField label="Studio facts" value={value.contactCopy.studioFacts} onChange={next => update('contactCopy', 'studioFacts', next)} /><JsonField label="Work prompts" value={value.contactCopy.workPrompts} onChange={next => update('contactCopy', 'workPrompts', next)} /></section>
    <section className="admin-card space-y-5 rounded-2xl p-5"><h3 className="font-semibold text-gray-800">Homepage interface copy</h3><p className="text-sm text-gray-500">These fields control the visible labels and supporting copy across Work, Skills, History, Reports, Contact, and Footer.</p><div className="grid gap-4 md:grid-cols-2">{(['projects', 'skills', 'experience', 'testimonials', 'contact', 'footer'] as const).map(section => <div key={section} className="space-y-3 rounded-xl border border-gray-200 p-4"><h4 className="font-medium capitalize text-gray-700">{section}</h4>{Object.entries(value.uiCopy[section]).filter(([key, field]) => typeof field === 'string' && key !== 'menuDescription').map(([key, field]) => <div key={key}>{bilingual(key, `uiCopy.${section}.${key}`, String(field), next => updateUi(section, key, next), key === 'heading' || key === 'body' || key === 'footnote' || key === 'footerSecondary')}</div>)}</div>)}</div></section>
  </div>
}
