CREATE TABLE IF NOT EXISTS site_pages (
  page_key TEXT PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'::JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS year TEXT;
ALTER TABLE initiatives ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::JSONB;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS org TEXT;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS points JSONB NOT NULL DEFAULT '[]'::JSONB;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS read_minutes INT NOT NULL DEFAULT 5;
ALTER TABLE news_posts ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS news_posts_slug_unique_idx
  ON news_posts (slug)
  WHERE slug IS NOT NULL;

ALTER TABLE site_pages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE site_pages FROM anon, authenticated;
